//! Method, error and parameter types for the BusinessServices endpoint.
#![allow(
    unused_imports,
)]
/* 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


use crate::{
    BaseOption, BaseRequest, Praiya, PaginatedResponse, PaginationQueryComponent,
    SingleResponse, SubSystem, DEFAULT_PAGERDUTY_API_LIMIT
};
use crate::errors::Error;
use crate::models::*;

use std::collections::HashMap;
use std::sync::Arc;

use futures_core::Stream;
use futures_util::stream::StreamExt;
use http::request::Builder;
use hyper::{Body, Method};
use serde::{Deserialize, Serialize};
use serde_json::value::Value;
use url::form_urlencoded;

pub struct BusinessServicesClient {
    pub(crate) api_endpoint: String,
    pub(crate) workspace: String,
    pub(crate) client: Praiya,
}



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct ListBusinessServicesListResponse {
    pub offset: usize,
    pub more: bool,
    pub limit: usize,
    pub total: Option<u64>,
    pub list_business_services: Vec<BusinessService>, //pub slack_connections: Vec<SlackConnection>
}

/// Query parameters for the [List business services](BusinessServices::list_business_services()) endpoint.
#[derive(Default, Serialize)]
pub struct BusinessServicesListBusinessServicesParams {
    pub(crate) qs: String,
}

pub struct BusinessServicesListBusinessServicesParamsBuilder<'req> {
    qs: form_urlencoded::Serializer<'req, String>,
}

impl<'req> BusinessServicesListBusinessServicesParamsBuilder<'req> {
    pub fn new() -> Self {
        Self {
            qs: form_urlencoded::Serializer::new(String::new())
        }
    }

    /// Offset to start pagination search results.
    pub fn offset(&mut self, offset: i32) -> &mut Self {
        self.qs.append_pair("offset", &offset);

        self
    }

    /// Limit on number of results to load
    pub fn limit(&mut self, limit: i32) -> &mut Self {
        self.qs.append_pair("limit", &limit);

        self
    }
}

impl BaseOption for BusinessServicesListBusinessServicesParams {
    fn build_paginated_query_string(&self, pagination: PaginationQueryComponent) -> String {
      let mut query = form_urlencoded::Serializer::new(self.qs.clone());
      query.append_pair("offset", &pagination.offset.to_string());
        query.append_pair("offset", &pagination.limit.to_string());
        query.finish()
    }
}

impl BusinessServicesClient {
    /// ---
    ///
    /// # Create a business service
    ///
    /// Create a new business service.
    /// 
    /// Business services model capabilities that span multiple technical services and that may be owned by several different teams.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#business-services)
    /// 
    /// 
    /// ---
    pub async fn create_business_service(&self, body: CreateBusinessServiceBody) -> Result<UpdateBusinessServiceResponse, Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, &self.path(), "")?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::POST),
            Some(Praiya::serialize_payload(CreateBusinessServiceBody)?));


        self.client
            .process_into_value(req)
            .await
    }

    /// ---
    ///
    /// # Delete a business service
    ///
    /// Delete an existing business service. 
    /// 
    /// Once the service is deleted, it will not be accessible from the web UI and new incidents won't be able to be created for this service.
    /// 
    /// Business services model capabilities that span multiple technical services and that may be owned by several different teams.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#business-services)
    /// 
    /// 
    /// ---
    pub async fn delete_business_service(&self, id: &str) -> Result<(), Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, format!("{}/{}", &self.path(), &id), "")?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::DELETE),
            Body::empty());


        self.client
            .process_into_value(req)
            .await
    }

    /// ---
    ///
    /// # Get a business service
    ///
    /// Get details about an existing business service.
    /// 
    /// Business services model capabilities that span multiple technical services and that may be owned by several different teams.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#business-services)
    /// 
    /// 
    /// ---
    pub async fn get_business_service(&self, id: &str) -> Result<UpdateBusinessServiceResponse, Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, format!("{}/{}", &self.path(), &id), "")?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::GET),
            Body::empty());


        self.client
            .process_into_value(req)
            .await
    }

    /// ---
    ///
    /// # List business services
    ///
    /// List existing business services.
    /// 
    /// Business services model capabilities that span multiple technical services and that may be owned by several different teams.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#business-services)
    /// 
    /// 
    /// ---
    pub fn list_business_services(&self, query_params: BusinessServicesListBusinessServicesParams) -> impl Stream<Item = Result<BusinessService, Error>> + '_ {
        let base_request = BaseRequest {
            host: String::clone(&self.api_endpoint),
            method: Method::GET,
            options: Arc::new(BusinessServicesListBusinessServicesParamsBuilder::new().build()),
            path: self.path(),
        };

        self.client
            .process_into_paginated_stream::<ListBusinessServicesResponse, ListBusinessServicesListResponse>(
                base_request,
                PaginationQueryComponent {
                    offset: 0,
                    limit: DEFAULT_PAGERDUTY_API_LIMIT,
                },
            )
            .boxed()

    }

    /// ---
    ///
    /// # Update a business service
    ///
    /// Update an existing business service. NOTE that this endpoint also accepts the PATCH verb.
    /// 
    /// Business services model capabilities that span multiple technical services and that may be owned by several different teams.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#business-services)
    /// 
    /// 
    /// ---
    pub async fn update_business_service(&self, id: &str, body: UpdateBusinessServiceBody) -> Result<UpdateBusinessServiceResponse, Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, format!("{}/{}", &self.path(), &id), "")?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::PUT),
            Some(Praiya::serialize_payload(UpdateBusinessServiceBody)?));


        self.client
            .process_into_value(req)
            .await
    }

}
