//! Method, error and parameter types for the ExtensionSchemas endpoint.
#![allow(
    unused_imports,
)]
/* 
 * PagerDuty API
 *
 * This document describes the PagerDuty REST APIs.  For guides and examples please visit our [Documentation.](https://developer.pagerduty.com/docs/get-started/getting-started/)  Our REST APIs are defined in OpenAPI v3.x. You can view the schema at [github.com/PagerDuty/api-schema](https://github.com/PagerDuty/api-schema). 
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@pagerduty.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::Deserialize;

use crate::models::*;

use std::collections::HashMap;
use serde_json::value::Value;

pub struct ExtensionSchemasClient {
    pub(crate) api_endpoint: String,
    pub(crate) client: PagerDuty,
}



impl BaseOption for ExtensionSchemasGetExtensionSchemaParams {
    fn build_paginated_query_string(&self, pagination: PaginationQueryComponent) -> String {
        let mut query = form_urlencoded::Serializer::new(form_urlencoded::Serializer::Clone(&self.qs))
        query.append_pair("offset", &pagination.offset.to_string());
        query.append_pair("offset", &pagination.limit.to_string());
        query.finish()
    }
}
/// Query parameters for the [List extension schemas](ExtensionSchemas::list_extension_schemas()) endpoint.
#[derive(Default, Serialize)]
pub struct ExtensionSchemasListExtensionSchemasParams<'req> {
    pub(crate) qs: String,
}

pub struct ExtensionSchemasListExtensionSchemasParamsBuilder {
    qs: form_urlencoded::Serializer<'req, String>,
}

impl<'req> ExtensionSchemasListExtensionSchemasParamsBuilder<'req> {
    pub fn new() -> Self {
        Self {
            qs: form_urlencoded::Serializer::new(String::new())
        }
    }
}


impl BaseOption for ExtensionSchemasListExtensionSchemasParams {
    fn build_paginated_query_string(&self, pagination: PaginationQueryComponent) -> String {
        let mut query = form_urlencoded::Serializer::new(form_urlencoded::Serializer::Clone(&self.qs))
        query.append_pair("offset", &pagination.offset.to_string());
        query.append_pair("offset", &pagination.limit.to_string());
        query.finish()
    }
}

impl ExtensionSchemasClient {
    /// ---
    ///
    /// # Get an extension vendor
    ///
    /// Get details about one specific extension vendor.
    /// 
    /// A PagerDuty extension vendor represents a specific type of outbound extension such as Generic Webhook, Slack, ServiceNow.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#extension-schemas)
    /// 
    /// 
    /// ---
    pub async fn get_extension_schema(&self, id: &str) -> Result<GetExtensionSchemaResponse, Error> {
        let uri = PagerDuty::parse_url(&self.api_endpoint, format!("{}/{}", &self.path(), &id), "")?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::GET),
            Body::empty());


        self.client
            .process_into_value(req)
            .await
    }

    /// ---
    ///
    /// # List extension schemas
    ///
    /// List all extension schemas.
    /// 
    /// A PagerDuty extension vendor represents a specific type of outbound extension such as Generic Webhook, Slack, ServiceNow.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#extension-schemas)
    /// 
    /// 
    /// ---
    pub fn list_extension_schemas(&self, query_params: ExtensionSchemasListExtensionSchemasParams) -> impl Stream<Item = Result<ExtensionSchema, Error>> + '_ {
        let base_request = BaseRequest {
            host: String::clone(&self.api_endpoint),
            method: Method::GET,
            options: Arc::new(ExtensionSchemasListExtensionSchemasParamsBuilder::new().build()),
            path: self.path(),
        };

        self.client
            .process_into_paginated_stream::<ExtensionSchemasResponse, >
    }

}
