//! Endpoints module and `PerPage` struct/impl
/*
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

pub mod incidents;
pub mod users;
pub mod services;
pub mod slack_connections;
