//! Method, error and parameter types for the OnCalls endpoint.
#![allow(
    unused_imports,
)]
/* 
 * PagerDuty API
 *
 * This document describes the PagerDuty REST APIs.  For guides and examples please visit our [Documentation.](https://developer.pagerduty.com/docs/get-started/getting-started/)  Our REST APIs are defined in OpenAPI v3.x. You can view the schema at [github.com/PagerDuty/api-schema](https://github.com/PagerDuty/api-schema). 
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@pagerduty.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

use serde::Deserialize;

use crate::models::*;

use std::collections::HashMap;
use serde_json::value::Value;

pub struct OnCallsClient {
    pub(crate) api_endpoint: String,
    pub(crate) client: PagerDuty,
}


/// Query parameters for the [List all of the on-calls](OnCalls::list_on_calls()) endpoint.
#[derive(Default, Serialize)]
pub struct OnCallsListOnCallsParams<'req> {
    pub(crate) qs: String,
}

pub struct OnCallsListOnCallsParamsBuilder {
    qs: form_urlencoded::Serializer<'req, String>,
}

impl<'req> OnCallsListOnCallsParamsBuilder<'req> {
    pub fn new() -> Self {
        Self {
            qs: form_urlencoded::Serializer::new(String::new())
        }
    }

    /// Time zone in which dates in the result will be rendered.
    pub fn time_zone(&mut self, time_zone: &'req str) -> &mut Self {
        self.qs.append_pair("time_zone", serde_urlencoded::to_string(time_zone));

        self
    }

    /// Array of additional details to include.
    pub fn include<I: IntoIterator<Item = &'req str>>(&mut self, include: I) -> &mut Self {
        for item in include {
            self.qs.append_pair("include[]", serde_urlencoded::to_string(item));
        }
        self
    }

    /// Filters the results, showing only on-calls for the specified user IDs.
    pub fn user_ids<I: IntoIterator<Item = &'req str>>(&mut self, user_ids: I) -> &mut Self {
        for item in user_ids {
            self.qs.append_pair("user_ids[]", serde_urlencoded::to_string(item));
        }
        self
    }

    /// Filters the results, showing only on-calls for the specified escalation policy IDs.
    pub fn escalation_policy_ids<I: IntoIterator<Item = &'req str>>(&mut self, escalation_policy_ids: I) -> &mut Self {
        for item in escalation_policy_ids {
            self.qs.append_pair("escalation_policy_ids[]", serde_urlencoded::to_string(item));
        }
        self
    }

    /// Filters the results, showing only on-calls for the specified schedule IDs. If `null` is provided in the array, it includes permanent on-calls due to direct user escalation targets.
    pub fn schedule_ids<I: IntoIterator<Item = &'req str>>(&mut self, schedule_ids: I) -> &mut Self {
        for item in schedule_ids {
            self.qs.append_pair("schedule_ids[]", serde_urlencoded::to_string(item));
        }
        self
    }

    /// The start of the time range over which you want to search. If an on-call period overlaps with the range, it will be included in the result. Defaults to current time. The search range cannot exceed 3 months.
    pub fn since(&mut self, since: chrono::DateTime<chrono::Utc>) -> &mut Self {
        self.qs.append_pair("since", serde_urlencoded::to_string(since));

        self
    }

    /// The end of the time range over which you want to search. If an on-call period overlaps with the range, it will be included in the result. Defaults to current time. The search range cannot exceed 3 months, and the `until` time cannot be before the `since` time.
    pub fn until(&mut self, until: chrono::DateTime<chrono::Utc>) -> &mut Self {
        self.qs.append_pair("until", serde_urlencoded::to_string(until));

        self
    }

    /// This will filter on-calls such that only the earliest on-call for each combination of escalation policy, escalation level, and user is returned. This is useful for determining when the \"next\" on-calls are for a given set of filters.
    pub fn earliest(&mut self, earliest: bool) -> &mut Self {
        self.qs.append_pair("earliest", serde_urlencoded::to_string(earliest));

        self
    }
}


impl BaseOption for OnCallsListOnCallsParams {
    fn build_paginated_query_string(&self, pagination: PaginationQueryComponent) -> String {
        let mut query = form_urlencoded::Serializer::new(form_urlencoded::Serializer::Clone(&self.qs))
        query.append_pair("offset", &pagination.offset.to_string());
        query.append_pair("offset", &pagination.limit.to_string());
        query.finish()
    }
}

impl OnCallsClient {
    /// ---
    ///
    /// # List all of the on-calls
    ///
    /// List the on-call entries during a given time range.
    /// 
    /// An on-call represents a contiguous unit of time for which a User will be on call for a given Escalation Policy and Escalation Rules.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#on-calls)
    /// 
    /// 
    /// ---
    pub fn list_on_calls(&self, query_params: OnCallsListOnCallsParams) -> impl Stream<Item = Result<Oncall, Error>> + '_ {
        let base_request = BaseRequest {
            host: String::clone(&self.api_endpoint),
            method: Method::GET,
            options: Arc::new(OnCallsListOnCallsParamsBuilder::new().build()),
            path: self.path(),
        };

        self.client
            .process_into_paginated_stream::<OnCallsResponse, >
    }

}
