//! Method, error and parameter types for the Users endpoint.
#![allow(
    unused_imports,
)]
/* 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


use crate::{
    BaseOption, BaseRequest, Praiya, PaginatedResponse, PaginationQueryComponent,
    SingleResponse, SubSystem, DEFAULT_PAGERDUTY_API_LIMIT
};
use crate::errors::Error;
use crate::models::*;

use std::collections::HashMap;
use std::sync::Arc;

use futures_core::Stream;
use futures_util::stream::StreamExt;
use http::request::Builder;
use hyper::{Body, Method};
use serde::{Deserialize, Serialize};
use serde_json::value::Value;
use url::form_urlencoded;

pub struct UsersClient {
    pub(crate) api_endpoint: String,
    pub(crate) workspace: String,
    pub(crate) client: Praiya,
}


/// Query parameters for the [Get the current user](Users::get_current_user()) endpoint.
#[derive(Default, Serialize)]
pub struct UsersGetCurrentUserParams {
    pub(crate) qs: String,
}

pub struct UsersGetCurrentUserParamsBuilder<'req> {
    qs: form_urlencoded::Serializer<'req, String>,
}

impl<'req> UsersGetCurrentUserParamsBuilder<'req> {
    pub fn new() -> Self {
        Self {
            qs: form_urlencoded::Serializer::new(String::new())
        }
    }

    /// Array of additional Models to include in response.
    pub fn include<I: IntoIterator<Item = &'req str>>(&mut self, include: I) -> &mut Self {
        for item in include {
            self.qs.append_pair("include[]", &item);
        }
        self
    }
}

impl BaseOption for UsersGetCurrentUserParams {
    fn build_paginated_query_string(&self, pagination: PaginationQueryComponent) -> String {
      let mut query = form_urlencoded::Serializer::new(self.qs.clone());
      query.append_pair("offset", &pagination.offset.to_string());
        query.append_pair("offset", &pagination.limit.to_string());
        query.finish()
    }
}
/// Query parameters for the [Get a user](Users::get_user()) endpoint.
#[derive(Default, Serialize)]
pub struct UsersGetUserParams {
    pub(crate) qs: String,
}

pub struct UsersGetUserParamsBuilder<'req> {
    qs: form_urlencoded::Serializer<'req, String>,
}

impl<'req> UsersGetUserParamsBuilder<'req> {
    pub fn new() -> Self {
        Self {
            qs: form_urlencoded::Serializer::new(String::new())
        }
    }

    /// Array of additional Models to include in response.
    pub fn include<I: IntoIterator<Item = &'req str>>(&mut self, include: I) -> &mut Self {
        for item in include {
            self.qs.append_pair("include[]", &item);
        }
        self
    }
}

impl BaseOption for UsersGetUserParams {
    fn build_paginated_query_string(&self, pagination: PaginationQueryComponent) -> String {
      let mut query = form_urlencoded::Serializer::new(self.qs.clone());
      query.append_pair("offset", &pagination.offset.to_string());
        query.append_pair("offset", &pagination.limit.to_string());
        query.finish()
    }
}
/// Query parameters for the [Get a user&#x27;s notification rule](Users::get_user_notification_rule()) endpoint.
#[derive(Default, Serialize)]
pub struct UsersGetUserNotificationRuleParams {
    pub(crate) qs: String,
}

pub struct UsersGetUserNotificationRuleParamsBuilder<'req> {
    qs: form_urlencoded::Serializer<'req, String>,
}

impl<'req> UsersGetUserNotificationRuleParamsBuilder<'req> {
    pub fn new() -> Self {
        Self {
            qs: form_urlencoded::Serializer::new(String::new())
        }
    }

    /// Array of additional details to include.
    pub fn include<I: IntoIterator<Item = &'req str>>(&mut self, include: I) -> &mut Self {
        for item in include {
            self.qs.append_pair("include[]", &item);
        }
        self
    }
}

impl BaseOption for UsersGetUserNotificationRuleParams {
    fn build_paginated_query_string(&self, pagination: PaginationQueryComponent) -> String {
      let mut query = form_urlencoded::Serializer::new(self.qs.clone());
      query.append_pair("offset", &pagination.offset.to_string());
        query.append_pair("offset", &pagination.limit.to_string());
        query.finish()
    }
}
/// Query parameters for the [List a user&#x27;s notification rules](Users::get_user_notification_rules()) endpoint.
#[derive(Default, Serialize)]
pub struct UsersGetUserNotificationRulesParams {
    pub(crate) qs: String,
}

pub struct UsersGetUserNotificationRulesParamsBuilder<'req> {
    qs: form_urlencoded::Serializer<'req, String>,
}

impl<'req> UsersGetUserNotificationRulesParamsBuilder<'req> {
    pub fn new() -> Self {
        Self {
            qs: form_urlencoded::Serializer::new(String::new())
        }
    }

    /// Array of additional details to include.
    pub fn include<I: IntoIterator<Item = &'req str>>(&mut self, include: I) -> &mut Self {
        for item in include {
            self.qs.append_pair("include[]", &item);
        }
        self
    }
}

impl BaseOption for UsersGetUserNotificationRulesParams {
    fn build_paginated_query_string(&self, pagination: PaginationQueryComponent) -> String {
      let mut query = form_urlencoded::Serializer::new(self.qs.clone());
      query.append_pair("offset", &pagination.offset.to_string());
        query.append_pair("offset", &pagination.limit.to_string());
        query.finish()
    }
}
/// Query parameters for the [Get a user&#x27;s status update notification rule](Users::get_user_status_update_notification_rule()) endpoint.
#[derive(Default, Serialize)]
pub struct UsersGetUserStatusUpdateNotificationRuleParams {
    pub(crate) qs: String,
}

pub struct UsersGetUserStatusUpdateNotificationRuleParamsBuilder<'req> {
    qs: form_urlencoded::Serializer<'req, String>,
}

impl<'req> UsersGetUserStatusUpdateNotificationRuleParamsBuilder<'req> {
    pub fn new() -> Self {
        Self {
            qs: form_urlencoded::Serializer::new(String::new())
        }
    }

    /// Array of additional details to include.
    pub fn include<I: IntoIterator<Item = &'req str>>(&mut self, include: I) -> &mut Self {
        for item in include {
            self.qs.append_pair("include[]", &item);
        }
        self
    }
}

impl BaseOption for UsersGetUserStatusUpdateNotificationRuleParams {
    fn build_paginated_query_string(&self, pagination: PaginationQueryComponent) -> String {
      let mut query = form_urlencoded::Serializer::new(self.qs.clone());
      query.append_pair("offset", &pagination.offset.to_string());
        query.append_pair("offset", &pagination.limit.to_string());
        query.finish()
    }
}
/// Query parameters for the [List a user&#x27;s status update notification rules](Users::get_user_status_update_notification_rules()) endpoint.
#[derive(Default, Serialize)]
pub struct UsersGetUserStatusUpdateNotificationRulesParams {
    pub(crate) qs: String,
}

pub struct UsersGetUserStatusUpdateNotificationRulesParamsBuilder<'req> {
    qs: form_urlencoded::Serializer<'req, String>,
}

impl<'req> UsersGetUserStatusUpdateNotificationRulesParamsBuilder<'req> {
    pub fn new() -> Self {
        Self {
            qs: form_urlencoded::Serializer::new(String::new())
        }
    }

    /// Array of additional details to include.
    pub fn include<I: IntoIterator<Item = &'req str>>(&mut self, include: I) -> &mut Self {
        for item in include {
            self.qs.append_pair("include[]", &item);
        }
        self
    }
}

impl BaseOption for UsersGetUserStatusUpdateNotificationRulesParams {
    fn build_paginated_query_string(&self, pagination: PaginationQueryComponent) -> String {
      let mut query = form_urlencoded::Serializer::new(self.qs.clone());
      query.append_pair("offset", &pagination.offset.to_string());
        query.append_pair("offset", &pagination.limit.to_string());
        query.finish()
    }
}

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct ListUsersListResponse {
    pub offset: usize,
    pub more: bool,
    pub limit: usize,
    pub total: Option<u64>,
    pub list_users: Vec<User>, //pub slack_connections: Vec<SlackConnection>
}

/// Query parameters for the [List users](Users::list_users()) endpoint.
#[derive(Default, Serialize)]
pub struct UsersListUsersParams {
    pub(crate) qs: String,
}

pub struct UsersListUsersParamsBuilder<'req> {
    qs: form_urlencoded::Serializer<'req, String>,
}

impl<'req> UsersListUsersParamsBuilder<'req> {
    pub fn new() -> Self {
        Self {
            qs: form_urlencoded::Serializer::new(String::new())
        }
    }

    /// Filters the result, showing only the users whose names or email addresses match the query.
    pub fn query(&mut self, query: &'req str) -> &mut Self {
        self.qs.append_pair("query", &query);

        self
    }

    /// An array of team IDs. Only results related to these teams will be returned. Account must have the `teams` ability to use this parameter.
    pub fn team_ids<I: IntoIterator<Item = &'req str>>(&mut self, team_ids: I) -> &mut Self {
        for item in team_ids {
            self.qs.append_pair("team_ids[]", &item);
        }
        self
    }

    /// Array of additional Models to include in response.
    pub fn include<I: IntoIterator<Item = &'req str>>(&mut self, include: I) -> &mut Self {
        for item in include {
            self.qs.append_pair("include[]", &item);
        }
        self
    }
}

impl BaseOption for UsersListUsersParams {
    fn build_paginated_query_string(&self, pagination: PaginationQueryComponent) -> String {
      let mut query = form_urlencoded::Serializer::new(self.qs.clone());
      query.append_pair("offset", &pagination.offset.to_string());
        query.append_pair("offset", &pagination.limit.to_string());
        query.finish()
    }
}

impl UsersClient {
    /// ---
    ///
    /// # Create a user
    ///
    /// Create a new user. Note that you must also supply a `password` property to create a user--it will not be returned by any API.
    /// 
    /// Users are members of a PagerDuty account that have the ability to interact with Incidents and other data on the account.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#users)
    /// 
    /// 
    /// ---
    pub async fn create_user(&self, body: CreateUserBody) -> Result<UsersBody, Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, &self.path(), "")?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::POST),
            Some(Praiya::serialize_payload(CreateUserBody)?));


        self.client
            .process_into_value(req)
            .await
    }

    /// ---
    ///
    /// # Create a user contact method
    ///
    /// Create a new contact method for the User.
    /// 
    /// Users are members of a PagerDuty account that have the ability to interact with Incidents and other data on the account.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#users)
    /// 
    /// 
    /// ---
    pub async fn create_user_contact_method(&self, id: &str, body: CreateUserContactMethodBody) -> Result<UpdateUserContactMethodResponse, Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, format!("{}/{}", &self.path(), &id), "")?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::POST),
            Some(Praiya::serialize_payload(CreateUserContactMethodBody)?));


        self.client
            .process_into_value(req)
            .await
    }

    /// ---
    ///
    /// # Create a user notification rule
    ///
    /// Create a new notification rule.
    /// 
    /// Users are members of a PagerDuty account that have the ability to interact with Incidents and other data on the account.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#users)
    /// 
    /// 
    /// ---
    pub async fn create_user_notification_rule(&self, id: &str, body: CreateUserNotificationRuleBody) -> Result<IdNotificationRulesBody, Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, format!("{}/{}", &self.path(), &id), "")?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::POST),
            Some(Praiya::serialize_payload(CreateUserNotificationRuleBody)?));


        self.client
            .process_into_value(req)
            .await
    }

    /// ---
    ///
    /// # Create notification subcription
    ///
    /// Create a new Notification Subscription for the given user.
    /// 
    /// <!-- theme: warning -->
    /// > ### Early Access
    /// > This endpoint is in Early Access and may change at any time. You must pass in the X-EARLY-ACCESS header to access it.
    /// 
    /// ---
    pub async fn create_user_notification_subscription(&self, id: &str, body: CreateUserNotificationSubscriptionBody) -> Result<CreateUserNotificationSubscriptionResponse, Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, format!("{}/{}", &self.path(), &id), "")?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::POST),
            Some(Praiya::serialize_payload(CreateUserNotificationSubscriptionBody)?));


        self.client
            .process_into_value(req)
            .await
    }

    /// ---
    ///
    /// # Create a user status update notification rule
    ///
    /// Create a new status update notification rule.
    /// 
    /// Users are members of a PagerDuty account that have the ability to interact with Incidents and other data on the account.
    /// 
    /// <!-- theme: warning -->
    /// > ### Early Access
    /// > This endpoint is in Early Access and may change at any time. You must pass in the X-EARLY-ACCESS header to access it.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#users)
    /// 
    /// 
    /// ---
    pub async fn create_user_status_update_notification_rule(&self, id: &str, body: CreateUserStatusUpdateNotificationRuleBody) -> Result<InlineResponse2016, Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, format!("{}/{}", &self.path(), &id), "")?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::POST),
            Some(Praiya::serialize_payload(CreateUserStatusUpdateNotificationRuleBody)?));


        self.client
            .process_into_value(req)
            .await
    }

    /// ---
    ///
    /// # Delete a user
    ///
    /// Remove an existing user.
    /// 
    /// Returns 400 if the user has assigned incidents unless your [pricing plan](https://support.pagerduty.com/docs/offboarding) has the `offboarding` feature and the account is [configured](https://support.pagerduty.com/docs/offboarding#section-additional-configurations) appropriately.
    /// 
    /// Note that the incidents reassignment process is asynchronous and has no guarantee to complete before the api call return.
    /// 
    /// [*Learn more about `offboarding` feature*](https://support.pagerduty.com/docs/offboarding).
    /// 
    /// Users are members of a PagerDuty account that have the ability to interact with Incidents and other data on the account.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#users)
    /// 
    /// 
    /// ---
    pub async fn delete_user(&self, id: &str) -> Result<(), Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, format!("{}/{}", &self.path(), &id), "")?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::DELETE),
            Body::empty());


        self.client
            .process_into_value(req)
            .await
    }

    /// ---
    ///
    /// # Delete a user&#x27;s contact method
    ///
    /// Remove a user's contact method.
    /// 
    /// Users are members of a PagerDuty account that have the ability to interact with Incidents and other data on the account.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#users)
    /// 
    /// 
    /// ---
    pub async fn delete_user_contact_method(&self, id: &str, contact_method_id: &str) -> Result<(), Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, format!("{}/{}", &self.path(), &id&contact_method_id), "")?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::DELETE),
            Body::empty());


        self.client
            .process_into_value(req)
            .await
    }

    /// ---
    ///
    /// # Delete a user&#x27;s notification rule
    ///
    /// Remove a user's notification rule.
    /// 
    /// Users are members of a PagerDuty account that have the ability to interact with Incidents and other data on the account.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#users)
    /// 
    /// 
    /// ---
    pub async fn delete_user_notification_rule(&self, id: &str, notification_rule_id: &str) -> Result<(), Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, format!("{}/{}", &self.path(), &id&notification_rule_id), "")?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::DELETE),
            Body::empty());


        self.client
            .process_into_value(req)
            .await
    }

    /// ---
    ///
    /// # Delete a user&#x27;s session
    ///
    /// Delete a user's session.
    /// 
    /// Users are members of a PagerDuty account that have the ability to interact with Incidents and other data on the account.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#users)
    /// 
    /// 
    /// ---
    pub async fn delete_user_session(&self, id: &str, _type: &str, session_id: &str) -> Result<(), Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, format!("{}/{}", &self.path(), &id&_type&session_id), "")?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::DELETE),
            Body::empty());


        self.client
            .process_into_value(req)
            .await
    }

    /// ---
    ///
    /// # Delete all user sessions
    ///
    /// Delete all user sessions.
    /// 
    /// Users are members of a PagerDuty account that have the ability to interact with Incidents and other data on the account.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#users)
    /// 
    /// 
    /// ---
    pub async fn delete_user_sessions(&self, id: &str) -> Result<(), Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, format!("{}/{}", &self.path(), &id), "")?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::DELETE),
            Body::empty());


        self.client
            .process_into_value(req)
            .await
    }

    /// ---
    ///
    /// # Delete a user&#x27;s status update notification rule
    ///
    /// Remove a user's status update notification rule.
    /// 
    /// Users are members of a PagerDuty account that have the ability to interact with Incidents and other data on the account.
    /// 
    /// <!-- theme: warning -->
    /// > ### Early Access
    /// > This endpoint is in Early Access and may change at any time. You must pass in the X-EARLY-ACCESS header to access it.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#users)
    /// 
    /// 
    /// ---
    pub async fn delete_user_status_update_notification_rule(&self, id: &str, status_update_notification_rule_id: &str) -> Result<(), Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, format!("{}/{}", &self.path(), &id&status_update_notification_rule_id), "")?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::DELETE),
            Body::empty());


        self.client
            .process_into_value(req)
            .await
    }

    /// ---
    ///
    /// # Get the current user
    ///
    /// Get details about the current user. 
    /// 
    /// This endpoint can only be used with a [user-level API key](https://support.pagerduty.com/docs/using-the-api#section-generating-a-personal-rest-api-key) or a key generated through an OAuth flow. This will not work if the request is made with an account-level access token.
    /// 
    /// Users are members of a PagerDuty account that have the ability to interact with Incidents and other data on the account.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#users)
    /// 
    /// 
    /// ---
    pub async fn get_current_user(&self, query_params: UsersGetCurrentUserParams) -> Result<UsersIdBody, Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, &self.path(), UsersGetCurrentUserParamsBuilder::new().build().qs)?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::GET),
            Body::empty());


        self.client
            .process_into_value(req)
            .await
    }

    /// ---
    ///
    /// # Get a user
    ///
    /// Get details about an existing user.
    /// 
    /// Users are members of a PagerDuty account that have the ability to interact with Incidents and other data on the account.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#users)
    /// 
    /// 
    /// ---
    pub async fn get_user(&self, id: &str, query_params: UsersGetUserParams) -> Result<UsersBody, Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, format!("{}/{}", &self.path(), &id), UsersGetUserParamsBuilder::new().build().qs)?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::GET),
            Body::empty());


        self.client
            .process_into_value(req)
            .await
    }

    /// ---
    ///
    /// # Get a user&#x27;s contact method
    ///
    /// Get details about a User's contact method.
    /// 
    /// Users are members of a PagerDuty account that have the ability to interact with Incidents and other data on the account.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#users)
    /// 
    /// 
    /// ---
    pub async fn get_user_contact_method(&self, id: &str, contact_method_id: &str) -> Result<UpdateUserContactMethodResponse, Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, format!("{}/{}", &self.path(), &id&contact_method_id), "")?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::GET),
            Body::empty());


        self.client
            .process_into_value(req)
            .await
    }

    /// ---
    ///
    /// # List a user&#x27;s contact methods
    ///
    /// List contact methods of your PagerDuty user.
    /// 
    /// Users are members of a PagerDuty account that have the ability to interact with Incidents and other data on the account.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#users)
    /// 
    /// 
    /// ---
    pub async fn get_user_contact_methods(&self, id: &str) -> Result<GetUserContactMethodsResponse, Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, format!("{}/{}", &self.path(), &id), "")?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::GET),
            Body::empty());


        self.client
            .process_into_value(req)
            .await
    }

    /// ---
    ///
    /// # Get a user&#x27;s notification rule
    ///
    /// Get details about a user's notification rule.
    /// 
    /// Users are members of a PagerDuty account that have the ability to interact with Incidents and other data on the account.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#users)
    /// 
    /// 
    /// ---
    pub async fn get_user_notification_rule(&self, id: &str, notification_rule_id: &str, query_params: UsersGetUserNotificationRuleParams) -> Result<IdNotificationRulesBody, Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, format!("{}/{}", &self.path(), &id&notification_rule_id), UsersGetUserNotificationRuleParamsBuilder::new().build().qs)?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::GET),
            Body::empty());


        self.client
            .process_into_value(req)
            .await
    }

    /// ---
    ///
    /// # List a user&#x27;s notification rules
    ///
    /// List notification rules of your PagerDuty user.
    /// 
    /// Users are members of a PagerDuty account that have the ability to interact with Incidents and other data on the account.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#users)
    /// 
    /// 
    /// ---
    pub async fn get_user_notification_rules(&self, id: &str, query_params: UsersGetUserNotificationRulesParams) -> Result<GetUserNotificationRulesResponse, Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, format!("{}/{}", &self.path(), &id), UsersGetUserNotificationRulesParamsBuilder::new().build().qs)?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::GET),
            Body::empty());


        self.client
            .process_into_value(req)
            .await
    }

    /// ---
    ///
    /// # List notification subscriptions
    ///
    /// Retrieve a list of Notification Subscriptions the given user has.
    /// 
    /// <!-- theme: warning -->
    /// > ### Early Access
    /// > This endpoint is in Early Access and may change at any time. You must pass in the X-EARLY-ACCESS header to access it.
    /// 
    /// 
    /// ---
    pub async fn get_user_notification_subscriptions(&self, id: &str) -> Result<GetUserNotificationSubscriptionsResponse, Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, format!("{}/{}", &self.path(), &id), "")?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::GET),
            Body::empty());


        self.client
            .process_into_value(req)
            .await
    }

    /// ---
    ///
    /// # Get a user&#x27;s session
    ///
    /// Get details about a user's session.
    /// 
    /// Users are members of a PagerDuty account that have the ability to interact with Incidents and other data on the account.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#users)
    /// 
    /// 
    /// ---
    pub async fn get_user_session(&self, id: &str, _type: &str, session_id: &str) -> Result<GetUserSessionResponse, Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, format!("{}/{}", &self.path(), &id&_type&session_id), "")?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::GET),
            Body::empty());


        self.client
            .process_into_value(req)
            .await
    }

    /// ---
    ///
    /// # List a user&#x27;s active sessions
    ///
    /// List active sessions of a PagerDuty user.
    /// 
    /// Users are members of a PagerDuty account that have the ability to interact with Incidents and other data on the account.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#users)
    /// 
    /// 
    /// ---
    pub async fn get_user_sessions(&self, id: &str) -> Result<GetUserSessionsResponse, Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, format!("{}/{}", &self.path(), &id), "")?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::GET),
            Body::empty());


        self.client
            .process_into_value(req)
            .await
    }

    /// ---
    ///
    /// # Get a user&#x27;s status update notification rule
    ///
    /// Get details about a user's status update notification rule.
    /// 
    /// Users are members of a PagerDuty account that have the ability to interact with Incidents and other data on the account.
    /// 
    /// <!-- theme: warning -->
    /// > ### Early Access
    /// > This endpoint is in Early Access and may change at any time. You must pass in the X-EARLY-ACCESS header to access it.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#users)
    /// 
    /// 
    /// ---
    pub async fn get_user_status_update_notification_rule(&self, id: &str, status_update_notification_rule_id: &str, query_params: UsersGetUserStatusUpdateNotificationRuleParams) -> Result<GetUserStatusUpdateNotificationRuleResponse, Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, format!("{}/{}", &self.path(), &id&status_update_notification_rule_id), UsersGetUserStatusUpdateNotificationRuleParamsBuilder::new().build().qs)?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::GET),
            Body::empty());


        self.client
            .process_into_value(req)
            .await
    }

    /// ---
    ///
    /// # List a user&#x27;s status update notification rules
    ///
    /// List status update notification rules of your PagerDuty user.
    /// 
    /// Users are members of a PagerDuty account that have the ability to interact with Incidents and other data on the account.
    /// 
    /// <!-- theme: warning -->
    /// > ### Early Access
    /// > This endpoint is in Early Access and may change at any time. You must pass in the X-EARLY-ACCESS header to access it.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#users)
    /// 
    /// 
    /// ---
    pub async fn get_user_status_update_notification_rules(&self, id: &str, query_params: UsersGetUserStatusUpdateNotificationRulesParams) -> Result<GetUserStatusUpdateNotificationRulesResponse, Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, format!("{}/{}", &self.path(), &id), UsersGetUserStatusUpdateNotificationRulesParamsBuilder::new().build().qs)?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::GET),
            Body::empty());


        self.client
            .process_into_value(req)
            .await
    }

    /// ---
    ///
    /// # List users
    ///
    /// List users of your PagerDuty account, optionally filtered by a search query.
    /// 
    /// Users are members of a PagerDuty account that have the ability to interact with Incidents and other data on the account.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#users)
    /// 
    /// 
    /// ---
    pub fn list_users(&self, query_params: UsersListUsersParams) -> impl Stream<Item = Result<User, Error>> + '_ {
        let base_request = BaseRequest {
            host: String::clone(&self.api_endpoint),
            method: Method::GET,
            options: Arc::new(UsersListUsersParamsBuilder::new().build()),
            path: self.path(),
        };

        self.client
            .process_into_paginated_stream::<ListUsersResponse, ListUsersListResponse>(
                base_request,
                PaginationQueryComponent {
                    offset: 0,
                    limit: DEFAULT_PAGERDUTY_API_LIMIT,
                },
            )
            .boxed()

    }

    /// ---
    ///
    /// # List audit records for a user
    ///
    /// The response will include audit records with changes that are made to the identified user not changes made by the identified user.
    /// 
    /// 
    /// The returned records are sorted by the `execution_time` from newest to oldest.
    /// 
    /// See [`Cursor-based pagination`](https://developer.pagerduty.com/docs/rest-api-v2/pagination/) for instructions on how to paginate through the result set.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#audit-record).
    /// 
    /// <!-- theme: warning -->
    /// > ### Early Access
    /// > This endpoint's interface is under development and subject to change. Do not use it in production systems.
    /// > Your request must set an X-EARLY-ACCESS header with value `audit-early-access` to acknowledge this.
    /// >
    /// > Audit records for user and team resources started in August 2020 and records may be purged while the API is in early access.
    /// 
    /// 
    /// ---
    pub async fn list_users_audit_records(&self, id: &str) -> Result<ListUsersAuditRecordsResponse, Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, format!("{}/{}", &self.path(), &id), "")?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::GET),
            Body::empty());


        self.client
            .process_into_value(req)
            .await
    }

    /// ---
    ///
    /// # Remove notification subscription
    ///
    /// Unsubscribe the given User from Notifications on the matching subscribable entity.
    /// 
    /// <!-- theme: warning -->
    /// > ### Early Access
    /// > This endpoint is in Early Access and may change at any time. You must pass in the X-EARLY-ACCESS header to access it.
    /// 
    /// ---
    pub async fn unsubscribe_user_notification_subscription(&self, id: &str) -> Result<(), Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, format!("{}/{}", &self.path(), &id), "")?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::POST),
            Body::empty());


        self.client
            .process_into_value(req)
            .await
    }

    /// ---
    ///
    /// # Update a user
    ///
    /// Update an existing user. Note that you may also supply a `password` property--it will not be returned by any API.
    /// 
    /// Users are members of a PagerDuty account that have the ability to interact with Incidents and other data on the account.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#users)
    /// 
    /// 
    /// ---
    pub async fn update_user(&self, id: &str, body: UpdateUserBody) -> Result<UsersIdBody, Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, format!("{}/{}", &self.path(), &id), "")?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::PUT),
            Some(Praiya::serialize_payload(UpdateUserBody)?));


        self.client
            .process_into_value(req)
            .await
    }

    /// ---
    ///
    /// # Update a user&#x27;s contact method
    ///
    /// Update a User's contact method.
    /// 
    /// Users are members of a PagerDuty account that have the ability to interact with Incidents and other data on the account.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#users)
    /// 
    /// 
    /// ---
    pub async fn update_user_contact_method(&self, id: &str, contact_method_id: &str, body: UpdateUserContactMethodBody) -> Result<UpdateUserContactMethodResponse, Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, format!("{}/{}", &self.path(), &id&contact_method_id), "")?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::PUT),
            Some(Praiya::serialize_payload(UpdateUserContactMethodBody)?));


        self.client
            .process_into_value(req)
            .await
    }

    /// ---
    ///
    /// # Update a user&#x27;s notification rule
    ///
    /// Update a user's notification rule.
    /// 
    /// Users are members of a PagerDuty account that have the ability to interact with Incidents and other data on the account.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#users)
    /// 
    /// 
    /// ---
    pub async fn update_user_notification_rule(&self, id: &str, notification_rule_id: &str, body: UpdateUserNotificationRuleBody) -> Result<UpdateUserNotificationRuleResponse, Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, format!("{}/{}", &self.path(), &id&notification_rule_id), "")?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::PUT),
            Some(Praiya::serialize_payload(UpdateUserNotificationRuleBody)?));


        self.client
            .process_into_value(req)
            .await
    }

    /// ---
    ///
    /// # Update a user&#x27;s status update notification rule
    ///
    /// Update a user's status update notification rule.
    /// 
    /// Users are members of a PagerDuty account that have the ability to interact with Incidents and other data on the account.
    /// 
    /// <!-- theme: warning -->
    /// > ### Early Access
    /// > This endpoint is in Early Access and may change at any time. You must pass in the X-EARLY-ACCESS header to access it.
    /// 
    /// For more information see the [API Concepts Document](../../docs/CONCEPTS.md#users)
    /// 
    /// 
    /// ---
    pub async fn update_user_status_update_notification_rule(&self, id: &str, status_update_notification_rule_id: &str, body: UpdateUserStatusUpdateNotificationRuleBody) -> Result<UpdateUserStatusUpdateNotificationRuleResponse, Error> {
        let uri = Praiya::parse_url(&self.api_endpoint, format!("{}/{}", &self.path(), &id&status_update_notification_rule_id), "")?;
            
        let req = self.client.build_request(
            uri,
            Builder::new().method(Method::PUT),
            Some(Praiya::serialize_payload(UpdateUserStatusUpdateNotificationRuleBody)?));


        self.client
            .process_into_value(req)
            .await
    }

}
